In [1]:
import pandas as pd
import numpy as np

In [3]:
True_news = pd.read_csv('True.csv')
Fake_news = pd.read_csv('Fake.csv', low_memory=False)

In [4]:
True_news

,title,text,subject,date
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017"
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017"
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017"
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017"
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017"
...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017"
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017"
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017"
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017"
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017"

In [5]:
Fake_news

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 162,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23498,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23499,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23500,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23501,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
True_news['label'] = 0
Fake_news['label'] = 1

In [7]:
True_news

,title,text,subject,date,label
0,"As U.S. budget fight looms, Republicans flip t...",WASHINGTON (Reuters) - The head of a conservat...,politicsNews,"December 31, 2017",0
1,U.S. military to accept transgender recruits o...,WASHINGTON (Reuters) - Transgender people will...,politicsNews,"December 29, 2017",0
2,Senior U.S. Republican senator: 'Let Mr. Muell...,WASHINGTON (Reuters) - The special counsel inv...,politicsNews,"December 31, 2017",0
3,FBI Russia probe helped by Australian diplomat...,WASHINGTON (Reuters) - Trump campaign adviser ...,politicsNews,"December 30, 2017",0
4,Trump wants Postal Service to charge 'much mor...,SEATTLE/WASHINGTON (Reuters) - President Donal...,politicsNews,"December 29, 2017",0
...,...,...,...,...,...
21412,'Fully committed' NATO backs new U.S. approach...,BRUSSELS (Reuters) - NATO allies on Tuesday we...,worldnews,"August 22, 2017",0
21413,LexisNexis withdrew two products from Chinese ...,"LONDON (Reuters) - LexisNexis, a provider of l...",worldnews,"August 22, 2017",0
21414,Minsk cultural hub becomes haven from authorities,MINSK (Reuters) - In the shadow of disused Sov...,worldnews,"August 22, 2017",0
21415,Vatican upbeat on possibility of Pope Francis ...,MOSCOW (Reuters) - Vatican Secretary of State ...,worldnews,"August 22, 2017",0
21416,Indonesia to buy $1.14 billion worth of Russia...,JAKARTA (Reuters) - Indonesia will buy 11 Sukh...,worldnews,"August 22, 2017",0

In [8]:
Fake_news

,title,text,subject,date,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,...,Unnamed: 163,Unnamed: 164,Unnamed: 165,Unnamed: 166,Unnamed: 167,Unnamed: 168,Unnamed: 169,Unnamed: 170,Unnamed: 171,label
0,Donald Trump Sends Out Embarrassing New Year’...,Donald Trump just couldn t wish all Americans ...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
1,Drunk Bragging Trump Staffer Started Russian ...,House Intelligence Committee Chairman Devin Nu...,News,"December 31, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
2,Sheriff David Clarke Becomes An Internet Joke...,"On Friday, it was revealed that former Milwauk...",News,"December 30, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
3,Trump Is So Obsessed He Even Has Obama’s Name...,"On Christmas day, Donald Trump announced that ...",News,"December 29, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
4,Pope Francis Just Called Out Donald Trump Dur...,Pope Francis used his annual Christmas Day mes...,News,"December 25, 2017",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23497,McPain: John McCain Furious That Iran Treated ...,21st Century Wire says As 21WIRE reported earl...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23498,JUSTICE? Yahoo Settles E-mail Privacy Class-ac...,21st Century Wire says It s a familiar theme. ...,Middle-east,"January 16, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23499,Sunnistan: US and Allied ‘Safe Zone’ Plan to T...,Patrick Henningsen 21st Century WireRemember ...,Middle-east,"January 15, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23500,How to Blow $700 Million: Al Jazeera America F...,21st Century Wire says Al Jazeera America will...,Middle-east,"January 14, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1
23501,10 U.S. Navy Sailors Held by Iranian Military ...,21st Century Wire says As 21WIRE predicted in ...,Middle-east,"January 12, 2016",NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1

In [9]:
dataset1 = True_news[['text','label']]
dataset2 = Fake_news[['text','label']]

In [10]:
dataset1

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
21412  BRUSSELS (Reuters) - NATO allies on Tuesday we...      0
21413  LONDON (Reuters) - LexisNexis, a provider of l...      0
21414  MINSK (Reuters) - In the shadow of disused Sov...      0
21415  MOSCOW (Reuters) - Vatican Secretary of State ...      0
21416  JAKARTA (Reuters) - Indonesia will buy 11 Sukh...      0

[21417 rows x 2 columns]

In [11]:
dataset2

                                                    text  label
0      Donald Trump just couldn t wish all Americans ...      1
1      House Intelligence Committee Chairman Devin Nu...      1
2      On Friday, it was revealed that former Milwauk...      1
3      On Christmas day, Donald Trump announced that ...      1
4      Pope Francis used his annual Christmas Day mes...      1
...                                                  ...    ...
23497  21st Century Wire says As 21WIRE reported earl...      1
23498  21st Century Wire says It s a familiar theme. ...      1
23499  Patrick Henningsen  21st Century WireRemember ...      1
23500  21st Century Wire says Al Jazeera America will...      1
23501  21st Century Wire says As 21WIRE predicted in ...      1

[23502 rows x 2 columns]

In [12]:
dataset = pd.concat([dataset1, dataset2])

In [13]:
dataset

                                                    text  label
0      WASHINGTON (Reuters) - The head of a conservat...      0
1      WASHINGTON (Reuters) - Transgender people will...      0
2      WASHINGTON (Reuters) - The special counsel inv...      0
3      WASHINGTON (Reuters) - Trump campaign adviser ...      0
4      SEATTLE/WASHINGTON (Reuters) - President Donal...      0
...                                                  ...    ...
23497  21st Century Wire says As 21WIRE reported earl...      1
23498  21st Century Wire says It s a familiar theme. ...      1
23499  Patrick Henningsen  21st Century WireRemember ...      1
23500  21st Century Wire says Al Jazeera America will...      1
23501  21st Century Wire says As 21WIRE predicted in ...      1

[44919 rows x 2 columns]

In [14]:
dataset.shape

(44919, 2)

In [15]:
dataset.isnull().sum()

text     0
label    0
dtype: int64

In [16]:
dataset['label'].value_counts()

label
1    23502
0    21417
Name: count, dtype: int64

In [17]:
dataset = dataset.sample(frac = 1)

In [18]:
dataset

                                                    text  label
11108  Dem. candidate for Georgia congressional seat ...      1
15035  It s almost like a flip has switched. Politica...      1
7360   Terrorists attacked Brussels, Belgium in a tra...      1
17921  Pittsburgh s head coach Mike Tomlin showed his...      1
2625   WASHINGTON (Reuters) - Russia’s ambassador to ...      0
...                                                  ...    ...
16710  ISLAMABAD (Reuters) - Ties between the United ...      0
22438  Prof Michel Chossudovsky Global ReaseachThe me...      1
19234  FLORENCE, Italy (Reuters) - Prime Minister The...      0
15405  BEIJING (Reuters) - China said on Wednesday it...      0
320    WASHINGTON (Reuters) - As the U.S. Congress wo...      0

[44919 rows x 2 columns]

# NLP

In [19]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [20]:
ps = WordNetLemmatizer()

In [21]:
stopwords = stopwords.words('english')

In [22]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\lahan\AppData\Roaming\nltk_data...

True

In [27]:
def clean_row(row):
    
    row = row.lower()
    row = re.sub('[^a-zA-Z]', ' ', row)
    
    token = row.split()
    
    news = [ps.lemmatize(word) for word in token if not word in stopwords]
    
    cleanned_news = ' '.join(news)
    
    return cleanned_news

In [28]:
dataset['text']

11108    Dem. candidate for Georgia congressional seat ...
15035    It s almost like a flip has switched. Politica...
7360     Terrorists attacked Brussels, Belgium in a tra...
17921    Pittsburgh s head coach Mike Tomlin showed his...
2625     WASHINGTON (Reuters) - Russia’s ambassador to ...
                               ...
16710    ISLAMABAD (Reuters) - Ties between the United ...
22438    Prof Michel Chossudovsky Global ReaseachThe me...
19234    FLORENCE, Italy (Reuters) - Prime Minister The...
15405    BEIJING (Reuters) - China said on Wednesday it...
320      WASHINGTON (Reuters) - As the U.S. Congress wo...
Name: text, Length: 44919, dtype: object

In [29]:
dataset['text'] = dataset['text'].apply(lambda x : clean_row(x))

In [30]:
dataset['text']

11108    dem candidate georgia congressional seat ossof...
15035    almost like flip switched political pundit new...
7360     terrorist attacked brussels belgium tragedy le...
17921    pittsburgh head coach mike tomlin showed solid...
2625     washington reuters russia ambassador washingto...
                               ...
16710    islamabad reuters tie united state pakistan ve...
22438    prof michel chossudovsky global reaseachthe me...
19234    florence italy reuters prime minister theresa ...
15405    beijing reuters china said wednesday continue ...
320      washington reuters u congress worked reach agr...
Name: text, Length: 44919, dtype: object

In [31]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [35]:
vectorizer = TfidfVectorizer(max_features=50000, lowercase=False, ngram_range=(1, 2))

In [36]:
x = dataset.iloc[: 35000,0]
y = dataset.iloc[: 35000,1]

In [37]:
x

11108    dem candidate georgia congressional seat ossof...
15035    almost like flip switched political pundit new...
7360     terrorist attacked brussels belgium tragedy le...
17921    pittsburgh head coach mike tomlin showed solid...
2625     washington reuters russia ambassador washingto...
                               ...
4367     everyone involved donald trump campaign seems ...
10221    many left liberal medium hoping president trum...
13429    amman reuters jordan allow israel reopen embas...
5168     washington reuters president donald trump nomi...
5353     melbourne fla reuters president donald trump r...
Name: text, Length: 35000, dtype: object

In [38]:
y

11108    1
15035    1
7360     1
17921    1
2625     0
        ..
4367     1
10221    1
13429    0
5168     0
5353     0
Name: label, Length: 35000, dtype: int64

In [39]:
from sklearn.model_selection import train_test_split

In [41]:
train_data, test_data, train_label, test_label = train_test_split(x, y, test_size = 0.2, random_state =0)

In [43]:
vec_train_data = vectorizer.fit_transform(train_data)

In [46]:
 vec_train_data = vec_train_data.toarray()

In [47]:
vec_test_data = vectorizer.fit_transform(test_data)

In [48]:
 vec_test_data = vec_test_data.toarray()

In [49]:
 vec_train_data.shape , vec_test_data.shape

((28000, 50000), (7000, 50000))

In [50]:
 vec_train_data

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [52]:
train_data = pd.DataFrame(vec_train_data, columns=vectorizer.get_feature_names_out())
testing_data = pd.DataFrame(vec_test_data, columns=vectorizer.get_feature_names_out())

In [53]:
train_data

,aapl,aaron,aaron klein,ab,ababa,ababa reuters,aback,abadi,abadi office,abadi said,...,zor,zor city,zor province,zucker,zuckerberg,zuckerberg said,zulia,zuma,zurich,zurich reuters
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27995,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27996,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27997,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.192607,0.056988,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27998,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27999,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

# Model

In [55]:
from sklearn.naive_bayes import MultinomialNB

In [56]:
clf = MultinomialNB()

In [58]:
clf.fit(train_data, train_label)

MultinomialNB()

In [59]:
y_pred = clf.predict(testing_data)

In [60]:
test_label

9345     1
1976     0
1630     0
6495     0
16699    0
        ..
14196    0
19898    1
241      1
10676    1
20237    0
Name: label, Length: 7000, dtype: int64

In [61]:
y_pred

array([0, 0, 0, ..., 1, 1, 1])

In [62]:
from sklearn.metrics import accuracy_score

In [63]:
accuracy_score(test_label, y_pred)

0.687

In [65]:
y_pred_train = clf.predict(train_data)

In [66]:
accuracy_score(train_label, y_pred_train)

0.9593214285714285